Ecomment/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('community/', include('community.urls')),
    path('news/',include('news.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

community/urls.py
from django.urls import path

from . import views
from .views import PostMain, PostList,  PostCreate, PostUpdate, PostDetail, PostLike, PostUnlike, PostMyList, PostFavorite, PostFavoriteList,CategoryView
# PostDelete,
app_name = 'community'

urlpatterns = [
    path("", PostMain.as_view(), name="index"),
    path("list/",PostList.as_view(), name='list'),
    path("search/",views.search, name = 'search'),
    path("create/",PostCreate.as_view(), name ='create'),
    # path("delete/<int:pk>/",PostDelete.as_view(), name = 'delete'),
    path("delete/<int:post_id>/",views.post_delete, name = 'delete'),
    path("update/<int:pk>/",PostUpdate.as_view(), name = 'update'),
    path("detail/<int:pk>/",PostDetail.as_view(), name = 'detail'),


    path("like/<int:post_id>/",PostLike.as_view(), name='like'),
    path("unlike/<int:post_id>/",PostUnlike.as_view(), name='unlike'),
    path("favorite/<int:post_id>/",PostFavorite.as_view(), name='favorite'),

    path("favorite_list/",PostFavoriteList.as_view(), name='favorite_list'),
    path("mypost/",PostMyList.as_view(), name='mypost'),
    path('category/<str:cats>/',CategoryView, name='category'),

    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]



# 이미지 url 확실히 설정해서 사진 오류 없앰
from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf.urls import url

from .import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

community/models.py
from django.db import models
from django.conf import settings
from django.forms import forms
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=50)
    class Meta:
        ordering =['name']
    
    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user',null=True)
    title = models.CharField(max_length = 200,null=True)
    category = models.CharField(max_length=200, default='uncategorized')
    text = models.TextField(max_length = 1700, null=True)
    image = models.ImageField(upload_to= 'community/community_photo/%Y/%m/%d',null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True,null=True)
    updated = models.DateTimeField(auto_now=True)

    # comment = models.ManyToManyField(User, related_name='comment_post', blank=True)
    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    unlike = models.ManyToManyField(User, related_name='unlike_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)
    hits = models.PositiveIntegerField(default = 0)
    # # views = models.IntegerField

    def __str__(self):
        return str(self.title)
        # 입력받은 객체의 문자열 버전을 반환하는 함수 
        # 내장 str 클래스 의 생성자 메소드를 실행, 인자로 객체 전달 하는 것 

    class Meta:
        ordering = ['-created']
        # 모델의 정렬 순서 지정 : 여러개 지정 시 필드 이름을 리스트로 나열 
        # - 붙으면 내림차순, 기본은 오름차순

    def get_absolute_url(self):
        return reverse('community:list', args=[self.id])
    # views에서 return super가 나오면 자동으로 이 url이 실행
    # 왜 안되는거야ㅑㅑㅑ

    def update_hit(self):
        self.hits += 1
        self.save()

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length = 350,null=True)
    created = models.DateTimeField(auto_now_add=True,null=True)
    updated = models.DateTimeField(auto_now=True, null=True, blank=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)

community/forms.py
from django import forms
from .models import Post, Category, Comment

#cats= [('cosmetic','cosmetic'),('womens','womens'),('children','children'),('organic','organic')]
choices = Category.objects.all().values_list('name','name')
choice_list = []
for item in choices:
    choice_list.append(item)

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=('title','category','text','image',)

        widgets = {
            'title' : forms.TextInput(attrs={'class':'form-control','placeholder': "제목을 입력해 주세요", 'style':'width: 777px;'}),
            'category' : forms.Select(choices=choices,attrs={'class':'form-control','placeholder':'choose a category', 'style':'width: 112px;'},),
            'text': forms.Textarea(attrs={'class':'form-control', 'placeholder': "내용을 입력해 주세요", 'style':'width: 777px;',
            'rows': 15}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

community/views.py
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView,CreateView, DeleteView
from django.views.generic.detail import DetailView
from .models import *
from django.views.generic.base import View
from urllib.parse import urlparse
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib import messages

from django.core.paginator import Paginator
from .forms import PostForm, CommentForm


# class mypage(View):
#     def get(self, request):
#         posts = Post.objects.all()
#         my_posts_list = posts.filter(author = request.user)
#         my_posts_list=my_posts_list[:2]
#         return render(request, 'account/mypage.html', {'my_posts_list':my_posts_list})
class PostMain(View):
    model = Post
    template_name='community/post_main.html'
    cats = Category.objects.all()

    def get(self, request):

        newer_list = Post.objects.all().order_by('-created')
        newer_list=newer_list[:3]

        like_list = Post.objects.all().order_by('-like')
        like_list = like_list[:4]

        watch_list = Post.objects.all().order_by('-hits')
        watch_list = watch_list[:4]
  
        return render(request, 'community/post_main.html', {'like_list':like_list,'watch_list':watch_list, 'newer_list':newer_list})

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(PostMain,self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context


class PostList(ListView):
    model = Post
    template_name_suffix = '_list'
    context_object_name = 'Posts'
    paginate_by = 8
    #몇 개씩 나올지 수정하기 
    cats = Category.objects.all()

    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(PostList,self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        return context

def CategoryView(request,cats):
    category_posts = Post.objects.filter(category=cats)
    cat_menu = Category.objects.all()
    return render(request, 'community/categories.html',{'cats':cats,'category_posts':category_posts,'cat_menu':cat_menu})

class PostCreate(CreateView):
    model = Post
    form_class = PostForm
    template_name ='community/post_create.html'
    success_url ='/community/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            # 올바르다면
            form.instance.save()
           # messages.add_message(self.request, messages.INFO, '새 글이 등록되었습니다.')  # 첫번째, 초기지원
           #  messages.info(self.request, '새 글이 등록되었습니다.')  # 두번째, shortcut 형태
            return redirect('/community/list')
        else:
            # 올바르지 않다면
            messages.error(self.request, 'Error!')
            return self.render_to_response({'form': form})

class PostUpdate(UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update'
    success_url ='/community/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request,'수정 권한이 없습니다.')
            return HttpResponseRedirect('/community/list')
        else:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)

# class PostDelete(DeleteView):
#     model = Post
#     template_name_suffix = '_delete'
#     success_url ='/community/list'
#
#     def dispatch(self, request, *args, **kwargs):
#         object = self.get_object()
#         if object.author != request.user:
#             messages.warning(request, '삭제 권한이 없습니다. ')
#             return HttpResponseRedirect('/community/list')
#         else:
#             return super(PostDelete, self).dispatch(request, *args, **kwargs)
def post_delete(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('community:detail', post_id=post.post_id)
    else:
        post.delete()
    return redirect('community:list')

class PostDetail(DetailView):
    model = Post
    template_name_suffix = '_detail'

class PostLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
            #로그인 되어있는지 확인 
            # 로그인 해달라는 모달이나 알람 만들기 
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk=post_id)
                user = request.user
                if user in post.like.all():
                    post.like.remove(user)
                else:
                    post.like.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            #url 을 parse
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PostUnlike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
            #로그인 되어있는지 확인 
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk = post_id)
                user = request.user
                if user in post.unlike.all():
                    post.unlike.remove(user)
                else:
                    post.unlike.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            #url 을 parse
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PostFavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
            #로그인 되어있는지 확인 
        else:
            if 'post_id' in kwargs:
                post_id = kwargs['post_id']
                post = Post.objects.get(pk = post_id)
                user = request.user
                if user in post.favorite.all():
                    post.favorite.remove(user)
                else:
                    post.favorite.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            #url 을 parse
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)


class PostFavoriteList(ListView):
    model = Post
    # template_name ='community/'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PostFavoriteList, self).dispatch(request, *args, **kwargs)
    
    def get_queryset(self):
        user = self.request.user
        queryset = user.favorite_post.all()
        print(queryset)
        return queryset

class PostMyList(ListView):
    model = Post
    template_name = 'community/mypost.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저하세요! ')
            return HttpResponseRedirect('/')
        return super(PostMyList,self).dispatch(request, *args, **kwargs)

def comment_create(request, post_id):

    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.created = timezone.now()
            comment.post = post
            comment.save()
            # return redirect('community:detail', post_id=post.id)
            # return HttpResponseRedirect('/community/detail/')
            return redirect('community:detail', pk=post_id)
    # else:
    #     form = CommentForm()
    # context = {'form': form}
    # return render(request, 'community/comment_form.html', context)
    # return render(request, 'community/comment_form.html', context)

def comment_update(request, comment_id):

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('community:detail', post_id=comment.post.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.updated = timezone.now()
            comment.save()
            # return redirect('community:detail', post_id=comment.post.id)
            return redirect('community:detail', pk=comment.post_id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'community/comment_form.html', context)

def comment_delete(request, comment_id):

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('community:detail', post_id=comment.post_id)
    else:
        comment.delete()
    return redirect('community:detail', pk=comment.post_id)


def search(request):
    posts = Post.objects.all().order_by('-id')

    q = request.POST.get('q', "")

    if q:
        posts = posts.filter(title__icontains=q)
        return render(request, 'community/search_post.html', {'posts': posts, 'q': q})

    else:
        return render(request, 'community/search_post.html')

templates/community/categories.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
        <form class="form-inline m-5 float-right" action="{% url 'community:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>

    <div class="container">
        <!----Category menu -->
        <div class="col text-center my-4">
            {% for item in cat_menu %}
                <a style="font-size: 20px;margin: 6%;" href="{% url 'community:category' item %}"> {{ item }}</a>
            {%endfor%}
        </div>

        <!-- Modal -->
        {% if user.is_authenticated %}
            <a style="color:#439966;float: right;margin-bottom:2%;" href="{% url 'community:create' %}">글쓰기</a>

        {% else %}
            <a style="color:#439966;cursor:pointer;float:right;margin-bottom:2%" data-toggle="modal" data-target="#myModal"> 글쓰기 </a>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">경고</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            비회원은 권한이 없습니다.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div></div>
        {% endif %}
   <a class="write" style="color:#439966;float: right;margin-bottom:2%;" href="{% url 'community:list' %}">전체 목록&nbsp&nbsp</a>

        <div class="table-responsive">
            <table class="table">
                <thead>
                </thead>

                {% for object in category_posts %}
                    <tr>
                        <td><a href="{% url 'community:detail' object.id %}">
                            {% if object.image %}
                                <img src="{{ object.image.url }}" alt="..." class="img-thumbnail" style="width:100px;height:100px;">
                            {% else %}
                                <img src="/static/image/alt.png" alt="..." class="img-thumbnail" style="width:100px;height:100px;">
                            {% endif %}
                        </a></td>
                        <th scope="row"><a style="color: #000000;" href="{% url 'community:detail' object.id %}">{{object.title}}</a><br><span style="font-weight: normal">{{object.created}}</span>
                            <br><span style="display: block;margin-top:15px;color: #000000;font-weight: normal">{{object.author}}</span></th>

                        <td><span><a href="{% url 'community:favorite' object.id %}" class="float-right">{% if user in object.favorite.all %} <img src="/static/image/sc_active.png"> {%else%} <img src="/static/image/scrab.png">{% endif %}</a></span><p style="margin-top:65px;float:right; font-weight:normal;font-size:14px;color: #000000;">공감 <span> {{ object.like.all.count}} </span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp비공감 <span> {{ object.unlike.all.count}} </span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp조회수 <span> {{ object.hits }} </span></p></td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% include 'community/pagination.html' %}

    {% include 'footer.html' %}
{% endblock %}

templates/community/post_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

    <div class="my-5">
        <div class="update_hit">
            {{ post.update_hit }}
        </div>

        <div class="">
            {#      테두리 있는 게 더 나은 것 같은뎅..  border-style:none;#}
            <div class="card" style="border-style:none;width: 80%; margin:10px auto">

                <div class="card-body">
                    <h5 class="card-title" style="font-weight:bold;font-family: Noto Sans KR;font-size:18px;color: #000000;">제목: {{ object.title }}</h5>
                    <div class="float-right">
                        {% if user.is_authenticated %}
                            <a href="{% url 'community:like' object.id %}" class="mr-3 float-left">{% if user in object.like.all %} <img src="/static/image/like_active.png"> {%else%} <img src="/static/image/yes.png">{% endif %}</a>
                            <a href="{% url 'community:unlike' object.id %}" class="mr-3 float-left">{% if user in object.unlike.all %} <img src="/static/image/unlike_active.png"> {%else%} <img src="/static/image/no.png">{% endif %}</a>
                            <a href="{% url 'community:favorite' object.id %}" class="mr-3 float-left">{% if user in object.favorite.all %} <img src="/static/image/scrabs_active.png"> {%else%} <img src="/static/image/scrabs.png">{% endif %}</a>

                        {% else %}
                            <a style="cursor:pointer;" data-toggle="modal" data-target="#myModal"><img src="/static/image/like.png"></a>
                            <a style="cursor:pointer;" data-toggle="modal" data-target="#myModal"><img src="/static/image/unlike.png"></a>
                            <a style="cursor:pointer;" data-toggle="modal" data-target="#myModal"><img src="/static/image/scrabs.png"></a>
                            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title">경고</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        </div>
                                        <div class="modal-body">
                                            비회원은 권한이 없습니다.
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div></div>
                        {% endif %}
                    </div>
                    <pre class="card-text" style="font-weight: normal;color: #000000;font-size:18px; font-family: Noto Sans KR;">{{ object.author }}    <span style="color: #808080;">{{ object.created }}</span></pre>
                    <pre class="card-text post-item" style="font-weight: normal;color: #000000;font-size:18px;font-family: Noto Sans KR;color: #808080;">공감 {{ object.like.all.count}}    비공감 {{ object.unlike.all.count}}    조회수 {{ object.hits }}</pre>


                    <br>
                    <br>
                    <p class="card-text post-item" style="font-weight: normal;color: #000000;font-size:14px;font-family: Noto Sans KR;">{{ object.text }}</p>

                </div>
                {% if object.image %}
                    <img src="{{ object.image.url }}" style="margin:40px auto; width: 40%;" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    {% if user == object.author %}
                        <span style="float: right;" class="mt-4">
                        <a href="{% url 'community:update' object.id %}" class="card-link">수정하기</a><span>&nbsp&nbsp</span>
                        <a href="{% url 'community:delete' object.id %}" class="card-link">삭제하기</a>
                        </span>
                    {% endif %}
                </div>
                <div class="card-body post-footer">

                </div>
            </div>
        </div>
        <!-- 슬릭 슬라이더 -->

        <section class="visual" style="margin-left: 10%">
            <div><img src="/static/image/advertising.png" width="900" height="160"></div>
            <div><img src="/static/image/Rectangle%20279.png" width="900" height="160" ></div>
            <div><img src="/static/image/advertising.png" width="900" height="160"></div>
            <div><img src="/static/image/Rectangle%20279.png" width="900" height="160" ></div>
        </section>
        <script>
            $('.visual').slick(
                {
                    slide: 'div',		//슬라이드 되어야 할 태그 ex) div, li
                    infinite: true, 	//무한 반복 옵션
                    slidesToShow: 1,		// 한 화면에 보여질 컨텐츠 개수
                    slidesToScroll: 1,		//스크롤 한번에 움직일 컨텐츠 개수
                    speed: 250,	 // 다음 버튼 누르고 다음 화면 뜨는데까지 걸리는 시간(ms)
                    arrows: false, 		// 옆으로 이동하는 화살표 표시 여부
                    autoplay: true,			// 자동 스크롤 사용 여부
                    autoplaySpeed: 3000, 		// 자동 스크롤 시 다음으로 넘어가는데 걸리는 시간 (ms)
                    pauseOnHover: true,		// 슬라이드 이동	시 마우스 호버하면 슬라이더 멈추게 설정
                    vertical: false,		// 세로 방향 슬라이드 옵션
                    prevArrow: "<button type='button' class='slick-prev'>Previous</button>",		// 이전 화살표 모양 설정
                    nextArrow: "<button type='button' class='slick-next'>Next</button>",		// 다음 화살표 모양 설정
                    dotsClass: "slick-dots", 	//아래 나오는 페이지네이션(점) css class 지정
                    draggable: true, 	//드래그 가능 여부
                });
        </script>


        <!-- 댓글 Start -->

        <div class="container my-5">
            <form action="{% url 'community:comment_create' object.id %}" method="post" class="post-form my-3">
                {% csrf_token %}
                <div class="form-group">
                    <p style="float: left;margin-left: 10%">댓글 &nbsp&nbsp{{ post.comment_set.count }}개</p>
                    <textarea class="form-control"name="content" id="content" style="float: right;width:70%;margin-right: 10%;"
                              rows="3" placeholder="댓글 내용">{{ form.content.value|default_if_none:'' }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary" style="font-weight: bold;color: #41965E;background: #F0F0F0;float: right; margin-right: 10%">등록하기</button>
            </form>
        </div>


        {% if post.comment_set.count > 0 %}
            <div class="mt-3" style="float: right;width:80%;margin-right: 10%;">
                {% for comment in post.comment_set.all %}
                    <div class="py-2 text-muted mb-4">
                        <img src="/static/image/person.png" width="50" class="mx-3 mt-4">
                        <span style="color: #000000;font-size:14px;">
                <span style="font-weight: bold">{{ comment.author }}</span> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp{{ comment.created }}
                            {% if comment.updated %}
                                (수정:{{ comment.updated }})
                            {% endif %}
                            <span style="float: right;" class="mt-4">
                                {% if request.user == comment.author %}
                                    <a href="{% url 'community:comment_update' comment.id  %}" class="">수정</a><span>&nbsp&nbsp&nbsp&nbsp&nbsp</span>
                                    <a href="{% url 'community:comment_delete' comment.id  %}" class=""> 삭제</a>
                                {% else %}
                                    <a href="#" class=""> 신고</a>
                                    </span>
                                {% endif %}
            </span>
                        </span>
                        {% if user.is_authenticated %}
                            <p style="margin-left:10%; font-size:14px;color: #000000;font-weight: normal">{{ comment.content }}</p>
                        {% else %}
                            <p style="margin-left:10%; font-size:14px;color: #000000;font-weight: normal">비회원은 접근 권한이 없습니다.</p>
                        {% endif %}
                    </div>
                    {#        <hr>#}
                {% endfor %}
            </div>


        {% endif %}
        <!-- 댓글 End -->
    </div>


{% endblock %}

templates/community/post_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
        <form class="form-inline m-5 float-right" action="{% url 'community:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    {% comment %} 게시글 목록 화면  {% endcomment %}
    <div class="container">
        <!----Category menu -->
        <div class="col text-center my-4">
            {% for item in cat_menu %}
                <a style="font-size: 20px;margin: 6%;" href="{% url 'community:category' item %}"> {{ item }}</a>
            {%endfor%}
        </div>
        <!-- Modal -->
        {% if user.is_authenticated %}
            <a style="color: #439966;float: right;margin-bottom:2%;" href="{% url 'community:create' %}">글쓰기</a>
        {% else %}
            <a style="color: #439966;cursor:pointer;float:right;margin-bottom:2%" data-toggle="modal" data-target="#myModal"> 글쓰기 </a>
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">경고</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            비회원은 권한이 없습니다.
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div></div>
        {% endif %}

        <div class="table-responsive">
            <table class="table">
                <thead>
                </thead>

                {% for object in object_list %}
                    <tr>
                        <td><a href="{% url 'community:detail' object.id %}">
                            {% if object.image %}
                                <img src="{{ object.image.url }}" alt="..." class="img-thumbnail" style="width:100px;height:100px;">
                            {% else %}
                                <img src="/static/image/alt.png" alt="..." class="img-thumbnail" style="width:100px;height:100px;">
                            {% endif %}
                        </a></td>
                        <th scope="row"><a style="color: #000000;" href="{% url 'community:detail' object.id %}">{{object.title}}</a><br><span style="font-weight: normal">{{object.created}}</span>
                            <br><span style="display: block;margin-top:15px;color: #000000;font-weight: normal">{{object.author}}</span></th>

                        <td><span><a href="{% url 'community:favorite' object.id %}" class="float-right">{% if user in object.favorite.all %} <img src="/static/image/sc_active.png"> {%else%} <img src="/static/image/scrab.png">{% endif %}</a></span><p style="margin-top:65px;float:right; font-weight:normal;font-size:14px;color: #000000;">공감 <span> {{ object.like.all.count}} </span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp비공감
                         <span> {{ object.unlike.all.count}} </span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp조회수 <span> {{ object.hits }} </span></p></td>

                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    {% include 'community/pagination.html' %}

    {% include 'footer.html' %}
{% endblock %} 