Ecomment/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('community/', include('community.urls')),
    path('news/',include('news.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf.urls import url

from .import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

news/urls.py
from django.urls import path

from . import views
from .views import GetIndexView, GetPolicyView, GetIssueView,GetEnterpriseView,GetEtcView

app_name = 'news'

urlpatterns = [
    path('index/',GetIndexView.as_view(), name='index'),
    path('policy/',GetPolicyView.as_view(), name='policy'),
    path('issue/',GetIssueView.as_view(), name='issue'),
    path('enterprise/',GetEnterpriseView.as_view(), name='enterprise'),
    path('etc/',GetEtcView.as_view(), name='etc'),
    path("search/", views.search, name='search'),
]

news/models.py
from django.db import models

class SearchNews(models.Model):
    title = models.CharField(max_length = 200)
    link = models.URLField()
    img = models.URLField(null=True)
    content = models.TextField(max_length=300)
    etc = models.CharField(max_length = 150)

    def __str__(self):
        return str(self.title)

news/views.py
import requests, json, cssutils
from bs4 import BeautifulSoup
from django.db import IntegrityError
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from news.models import SearchNews
from django.core.paginator import Paginator
import os
## Python이 실행될 때 DJANGO_SETTINGS_MODULE이라는 환경 변수에 현재 프로젝트의 settings.py파일 경로를 등록합니다.
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "Ecomment.settings")
## 이제 장고를 가져와 장고 프로젝트를 사용할 수 있도록 환경을 만듭니다.
import django
django.setup()

class GetIndexView(View):
    def get(self, request):
    
        return render(request, 'news/index.html')

class GetPolicyView(View):
    
    model = SearchNews
    context_object_name = 'SearchNews'
    paginate_by = 8

    def get(self, request):
        policy_url = 'http://www.chemicalnews.co.kr/news/articleList.html?sc_section_code=S1N1&view_type=sm'
        req = requests.get(policy_url)
        req.encoding = 'utf-8'
        html = req.text

        soup = BeautifulSoup(html, 'html.parser')
        list_items = soup.find_all('div', class_='list-block')

        policy_data = []
        chemical = 'http://www.chemicalnews.co.kr/'

        for item in list_items:
            
            title = item.find('div',class_='list-titles').text

            link = item.find('div',class_='list-image').find('a')
            if 'href' in link.attrs:
                conn = link.attrs['href']

            image= item.find('div',class_='list-image')['style']
            
            style = cssutils.parseStyle(image)
            url = style['background-image']
            url = url.replace('url(.','').replace(')','')

            content = item.find('p',class_='list-summary').text

            etc = item.find('div',class_='list-dated').text
            
            policy_data.append(
                {
                'title': title,
                'link': chemical + conn,
                'img': chemical + 'news/'+ url,
                'content': content[0:150],
                'etc': etc
                }
            )
        return render(request, 'news/policy.html',{'policy_data' : policy_data})
        #     return policy_data

        # policy_data = policy()
        # for item in policy_data:
        #     t = item.get('title')
        #     l = item.get('link')
        #     i = item.get('img')
        #     c = item.get('content')
        #     e = item.get('etc')
        #     SearchNews(title=t, link=l,img=i, content=c,etc=e).save()

        # for t,l,i,c,e in policy_data.items():
        #     SearchNews(title=t, link=l).save()
            # return render(request, 'news/policy.html',{'policy_data' : policy_data})

class GetIssueView(View):
    def get(self, request):
        issue_url = 'http://www.chemicalnews.co.kr/news/articleList.html?sc_section_code=S1N3&view_type=sm'
        req = requests.get(issue_url)
        req.encoding = 'utf-8'
        html = req.text

        soup = BeautifulSoup(html, 'html.parser')
        list_items = soup.find_all('div', class_='list-block')

        issue_data = []
        chemical = 'http://www.chemicalnews.co.kr/'
        #chemical = 'http://www.newspenguin.com'

        for item in list_items:
            
            title = item.find('div',class_='list-titles').text

            link = item.find('div',class_='list-image').find('a')
            if 'href' in link.attrs:
                conn = link.attrs['href']

            image= item.find('div',class_='list-image')['style']
            
            style = cssutils.parseStyle(image)
            url = style['background-image']
            url = url.replace('url(.','').replace(')','')

            content = item.find('p',class_='list-summary').text

            etc = item.find('div',class_='list-dated').text
            
            issue_data.append(
                {
                'title': title,
                'link': chemical + conn,
                'img': chemical + 'news/'+ url,
                'content': content[0:150],
                'etc': etc
                }
            )
        return render(request, 'news/issue.html',{'issue_data' : issue_data})
        # return JsonResponse({'policy_data' : policy_data}, status = 200, json_dumps_params={'ensure_ascii': False})  
        # 결과를 JsonResponse 규격에 맞는 dictionary형태로 return해준다.

class GetEnterpriseView(View):
    def get(self, request):
        enter_url = 'http://www.newspenguin.com/news/articleList.html?sc_section_code=S1N5&view_type=sm'
        req = requests.get(enter_url)
        req.encoding = 'utf-8'
        html = req.text

        soup = BeautifulSoup(html, 'html.parser')
        list_items = soup.find_all('div', class_='list-block')

        enter_data = []
        chemical = 'http://www.newspenguin.com/'

        for item in list_items:
            
            title = item.find('div',class_='list-titles').text

            link = item.find('div',class_='list-image').find('a')
            if 'href' in link.attrs:
                conn = link.attrs['href']

            image= item.find('div',class_='list-image')['style']
            
            style = cssutils.parseStyle(image)
            url = style['background-image']
            url = url.replace('url(.','').replace(')','')

            content = item.find('p',class_='list-summary').text

            etc = item.find('div',class_='list-dated').text
            
            enter_data.append(
                {
                'title': title,
                'link': chemical + conn,
                'img': chemical + 'news/'+ url,
                'content': content[0:150],
                'etc': etc
                }
            )
        return render(request, 'news/enterprise.html',{'enter_data' : enter_data})
        # return JsonResponse({'policy_data' : policy_data}, status = 200, json_dumps_params={'ensure_ascii': False})  
        # 결과를 JsonResponse 규격에 맞는 dictionary형태로 return해준다.

class GetEtcView(View):
    def get(self, request):
        etc_url = 'http://www.newspenguin.com/news/articleList.html?sc_section_code=S1N9&view_type=sm'
        req = requests.get(etc_url)
        req.encoding = 'utf-8'
        html = req.text

        soup = BeautifulSoup(html, 'html.parser')
        list_items = soup.find_all('div', class_='list-block')

        etc_data = []
        #chemical = 'http://www.chemicalnews.co.kr/'
        chemical = 'http://www.newspenguin.com/'

        for item in list_items:
            
            title = item.find('div',class_='list-titles').text

            link = item.find('div',class_='list-image').find('a')
            if 'href' in link.attrs:
                conn = link.attrs['href']

            image= item.find('div',class_='list-image')['style']
            
            style = cssutils.parseStyle(image)
            url = style['background-image']
            url = url.replace('url(.','').replace(')','')

            content = item.find('p',class_='list-summary').text

            etc = item.find('div',class_='list-dated').text
            
            etc_data.append(
                {
                'title': title,
                'link': chemical + conn,
                'img': chemical + 'news/'+ url,
                'content': content[0:150],
                'etc': etc
                }
            )
        return render(request, 'news/etc.html',{'etc_data' : etc_data})
        # return JsonResponse({'policy_data' : policy_data}, status = 200, json_dumps_params={'ensure_ascii': False})  
        # 결과를 JsonResponse 규격에 맞는 dictionary형태로 return해준다.

def search(request):
    news = SearchNews.objects.all()

    q = request.POST.get('q', "")

    if q:
        news = news.filter(title__icontains=q)
        return render(request, 'news/search_news.html', {'news': news, 'q': q})

    else:
        return render(request, 'news/search_news.html')

templates/news/enterprise.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>
.image{
    width :250px;
}
.title_content{
    width : 650px;
}
.content{
 font-size : 0.9rem;
}
.etc{
 font-size : 0.8rem;
}   

</style>
        <form class="form-inline m-5 float-right" action="{% url 'news:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
<div class="col text-center my-4">

      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:policy'%}">정책</a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:issue'%}">친환경 이슈</a>
      <a style="font-size: 20px;margin: 6%;text-decoration : underline;text-underline-position: under; text-decoration-color: #439966;">친환경 기업 뉴스 </a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:etc'%}">기타</a>

</div>
{% comment %} 게시글 목록 화면  {% endcomment %}
<div class="container">
        <table class="table table-borderless">
            <thead>
                <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% for item in enter_data %}
                <tr>
                <td scope="row" class="image">
                    <a href="{{ item.link }}">
                    <img src="{{ item.img }}" alt="..." class="img-thumbnail" style="width:200px;height:150px;"></a>
                </td>
                <td class="title_content" colspan="3"><a style="color: #000000;" href="{{ item.link }}" >{{ item.title}}</a><br>
                <p><a href="{{ item.link }}"><small class="content">{{ item.content }}</small></a></p>
                <p><small class="etc">{{ item.etc }}</small></p>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% comment %} {% include 'community/pagination.html' %} {% endcomment %}

{% include 'footer.html' %}
{% endblock %} 

templates/news/etc.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>
.image{
    width :250px;
}
.title_content{
    width : 650px;
}
.content{
 font-size : 0.9rem;
}
.etc{
 font-size : 0.8rem;
}   

</style>
        <form class="form-inline m-5 float-right" action="{% url 'news:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
<div class="col text-center my-4">
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:policy'%}">정책</a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:issue'%}">친환경 이슈</a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:enterprise'%}">친환경 기업 뉴스 </a>
      <a style="font-size: 20px;margin: 6%;text-decoration : underline;text-underline-position: under; text-decoration-color: #439966;">기타</a>
</div>
{% comment %} 게시글 목록 화면  {% endcomment %}
<div class="container">
        <table class="table table-borderless">
            <thead>
                <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% for item in etc_data %}
                <tr>
                <td scope="row" class="image">
                    <a href="{{ item.link }}">
                    <img src="{{ item.img }}" alt="..." class="img-thumbnail" style="width:200px;height:150px;"></a>
                </td>
                <td class="title_content" colspan="3"><a style="color: #000000;" href="{{ item.link }}" >{{ item.title}}</a><br>
                <p><a href="{{ item.link }}"><small class="content">{{ item.content }}</small></a></p>
                <p><small class="etc">{{ item.etc }}</small></p>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% comment %} {% include 'community/pagination.html' %} {% endcomment %}

{% include 'footer.html' %}
{% endblock %} 

templates/news/index.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'news.css' %}">

<!-- 정보/ 뉴스 메인 화면 -->
    <form class="form-inline m-5 float-right" action="{% url 'news:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
<div class="container">
    <section class="visual">
        <div><img src="/static/image/advertising.png" width="100%" height="160" ></div>
    </section>
    <hr style="border: 1px solid #CDCDCD; margin : 30px 0; width:100%; ">
    <div class="header">뉴스</div>
    <div class="more"><a class="more-text" href="{% url 'news:policy'%}">더보기 </a></div>
    <div class="wrapper">
        <div>
         <a href="http://www.chemicalnews.co.kr//news/articleView.html?idxno=1972">
            <div class="news_image">
                <img src="/static/image/pol_1.jpg" width="100%" height="100%" >
            </div>
            <p class="title">코로나19로 인한 사회적 격리는 언제 끝낼 수 있나?</p>
            <p class="news_etc">2020.08.23 / <a class="cate_text" href="{% url 'news:policy'%}"> 정책 </a> </p>
         </a>
        </div>

        <div>
         <a href="http://www.chemicalnews.co.kr//news/articleView.html?idxno=2768">
            <div class="news_image">
                <img src="/static/image/pol_2.jpg" width="100%" height="100%" >
            </div>
            <p class="title">코로나19 치료제·백신 생산시설·장비 지원대상 기업 모집...예산 100억 원 확보 </p>
            <p class="news_etc">2020.08.12 / <a class="cate_text"  href="{% url 'news:issue'%}">친환경 이슈 </a> </p>
         </a>
        </div>

        <div>
           <a href="http://www.newspenguin.com//news/articleView.html?idxno=2273">
            <div class="news_image">
                <img src="/static/image/pol_3.jpg" width="100%" height="100%" >
            </div>
            <p class="title">덴마크 가구회사가 코로나19 재택근무 늘어나자 내놓은 이것 </p>
            <p class="news_etc">2020.08.16 / <a class="cate_text" href="{% url 'news:enterprise'%}"> 기업 </a>   </p>
           </a>
        </div>

        <div>
          <a href="http://www.newspenguin.com//news/articleView.html?idxno=2370">
            <div class="news_image">
                <img src="/static/image/pol_4.jpg" width="100%" height="100%" >
            </div>
            <p class="title">BGF에코바이오, 친환경 전문 브랜드 론칭해 CU 상품에 적용 </p>
            <p class="news_etc">2020.08.23 / <a class="cate_text"  href="{% url 'news:etc'%}"> 기타  </a>  </p>
          </a>
        </div>
    </div>
    <hr style="border: 1px solid #CDCDCD; margin : 30px 0; width:100%; ">
    <div class="camp">캠페인</div>
    <div class="campaign">
        <img src="/static/image/Rectangle 279.png" width="100%" height="100%" >
    </div>
    <div class="campaign">
        <img src="/static/image/Rectangle 280.png" width="100%" height="100%" >
    </div>
</div>


{% include 'footer.html' %}
{% endblock %} 

templates/news/issue.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>
.image{
    width :250px;
}
.title_content{
    width : 650px;
}
.content{
 font-size : 0.9rem;
}
.etc{
 font-size : 0.8rem;
}   
.now{
    text-decoration : underline;
    text-underline-position: under; 
    text-decoration-color: #439966;
}

</style>
        <form class="form-inline m-5 float-right" action="{% url 'news:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
<div class="col text-center my-4">
    <a style="font-size: 20px;margin: 6%;" href="{% url 'news:policy'%}">정책</a>
    <a style="font-size: 20px;margin: 6%;text-decoration : underline;text-underline-position: under; text-decoration-color: #439966;">친환경 이슈</a>
    <a style="font-size: 20px;margin: 6%;" href="{% url 'news:enterprise'%}">친환경 기업 뉴스 </a>
    <a style="font-size: 20px;margin: 6%;" href="{% url 'news:etc'%}">기타</a>
</div>
{% comment %} 게시글 목록 화면  {% endcomment %}
<div class="container">
        <table class="table table-borderless">
            <thead>
                <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% for item in issue_data %}
                 <tr>
                <td scope="row" class="image">
                    <a href="{{ item.link }}">
                    <img src="{{ item.img }}" alt="..." class="img-thumbnail" style="width:200px;height:150px;"></a>
                </td>
                <td class="title_content" colspan="3"><a style="color: #000000;" href="{{ item.link }}" >{{ item.title}}</a><br>
                <p><a href="{{ item.link }}"><small class="content">{{ item.content }}</small></a></p>
                <p><small class="etc">{{ item.etc }}</small></p>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% comment %} {% include 'community/pagination.html' %} {% endcomment %}

{% include 'footer.html' %}
{% endblock %} 

templates/news/policy.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<style>
.image{
    width :250px;
}
.title_content{
    width : 650px;
}
.content{
 font-size : 0.9rem;
}
.etc{
 font-size : 0.8rem;
}   

</style>
        <form class="form-inline m-5 float-right" action="{% url 'news:search' %}" method="post">
        {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
<div class="col text-center my-4">
      <a class="now" style="font-size: 20px;margin: 6%;text-decoration : underline;text-underline-position: under; text-decoration-color: #439966;">정책</a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:issue'%}">친환경 이슈</a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:enterprise'%}">친환경 기업 뉴스 </a>
      <a style="font-size: 20px;margin: 6%;" href="{% url 'news:etc'%}">기타</a>
</div>
{% comment %} 게시글 목록 화면  {% endcomment %}
<div class="container">
        <table class="table table-borderless">
            <thead>
                <tr>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
            {% for item in policy_data %}
                <tr>
                <td scope="row" class="image">
                    <a href="{{ item.link }}">
                    <img src="{{ item.img }}" alt="..." class="img-thumbnail" style="width:200px;height:150px;"></a>
                </td>
                <td class="title_content" colspan="3"><a style="color: #000000;" href="{{ item.link }}" >{{ item.title}}</a><br>
                <p><a href="{{ item.link }}"><small class="content">{{ item.content }}</small></a></p>
                <p><small class="etc">{{ item.etc }}</small></p>
                </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
</div>
{% comment %} {% include 'community/pagination.html' %} {% endcomment %}

{% include 'footer.html' %}
{% endblock %} 

templates/news/search_news.html
{% extends 'base.html' %}

{% block content %}
<div style="margin: 5% auto; width:70%;">
    <h2 class="my-5 text-center font-weight-bold">뉴스 검색결과</h2>
    {% if not news %}

        <h3 class="mt-5 text-center">'{{ q }}'에 대한 검색 결과가 없습니다</h3>

    {% else %}

        {% for new in news.all %}
        <div class="container my-2">
            <div class="card">
                <div class="card-body">
                    <h3>{{ new.title }}</h3>
{#                    <p><a href="{% post.link %}">...자세히 보기</a></p>#}
                </div>
            </div>
        </div>
        <br>
        {% endfor %}

    {% endif %}
</div>
{% endblock %}