Ecomment/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('community/', include('community.urls')),
    path('news/',include('news.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('checkbox/', views.checkbox, name='checkbox'),
    path('mypage/', views.mypage.as_view(), name='mypage')
]

community/urls.py
from django.urls import path

from . import views
from .views import PostMain, PostList,  PostCreate, PostUpdate, PostDetail, PostLike, PostUnlike, PostMyList, PostFavorite, PostFavoriteList,CategoryView
# PostDelete,
app_name = 'community'

urlpatterns = [
    path("", PostMain.as_view(), name="index"),
    path("list/",PostList.as_view(), name='list'),
    path("search/",views.search, name = 'search'),
    path("create/",PostCreate.as_view(), name ='create'),
    # path("delete/<int:pk>/",PostDelete.as_view(), name = 'delete'),
    path("delete/<int:post_id>/",views.post_delete, name = 'delete'),
    path("update/<int:pk>/",PostUpdate.as_view(), name = 'update'),
    path("detail/<int:pk>/",PostDetail.as_view(), name = 'detail'),


    path("like/<int:post_id>/",PostLike.as_view(), name='like'),
    path("unlike/<int:post_id>/",PostUnlike.as_view(), name='unlike'),
    path("favorite/<int:post_id>/",PostFavorite.as_view(), name='favorite'),

    path("favorite_list/",PostFavoriteList.as_view(), name='favorite_list'),
    path("mypost/",PostMyList.as_view(), name='mypost'),
    path('category/<str:cats>/',CategoryView, name='category'),

    path('comment/create/<int:post_id>/', views.comment_create, name='comment_create'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]



# 이미지 url 확실히 설정해서 사진 오류 없앰
from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.conf.urls import url

from .import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
]

news/urls.py
from django.urls import path

from . import views
from .views import GetIndexView, GetPolicyView, GetIssueView,GetEnterpriseView,GetEtcView

app_name = 'news'

urlpatterns = [
    path('index/',GetIndexView.as_view(), name='index'),
    path('policy/',GetPolicyView.as_view(), name='policy'),
    path('issue/',GetIssueView.as_view(), name='issue'),
    path('enterprise/',GetEnterpriseView.as_view(), name='enterprise'),
    path('etc/',GetEtcView.as_view(), name='etc'),
    path("search/", views.search, name='search'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render, redirect


# Create your views here.
def home(request):
    if request.method == 'GET':
        return render(request, 'home.html')

templates/base.html
<!doctype html>
{% load static %}
<html>
<head>
    <meta   charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo:wght@700&family=Roboto+Slab&family=Song+Myung&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/bootstrap.css">
    <link rel="stylesheet" href="{% static 'ecomment.css' %}">

    <!-- jQuery  -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <!--slick-->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <!-- JS, Popper.js-->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="{% static 'checkbox.js' %}"></script>

    <title>Ecomment</title>
</head>
<body>

<div class ="container" style="flex:1 0 auto">
    <nav class="navbar navbar-expand-lg my-1">
        <a class="navbar-brand" href="{% url 'home:home' %}">
            <svg width="77" height="76" viewBox="0 0 77 76" fill="none" xmlns="http://www.w3.org/2000/svg">
                <circle cx="38.7734" cy="38" r="38" fill="white"/>
                <ellipse cx="38.2734" cy="37.5" rx="28.1429" ry="13.5764" transform="rotate(45 38.2734 37.5)" fill="#41965E"/>
                <path d="M46.3533 30.4581C43.0463 35.1034 43.4122 41.4231 47.2334 45.6557L52.4152 51.3954L46.6755 46.2136C42.4429 42.3924 36.1233 42.0265 31.4779 45.3335C34.785 40.6882 34.419 34.3685 30.5978 30.136L25.416 24.3962L31.1558 29.578C35.3884 33.3992 41.708 33.7651 46.3533 30.4581Z" fill="#F8F7F4"/>
                <path d="M42.5686 58.7142C30.9 52.1042 24.5767 46.2844 17.1508 33.1743C20.1328 42.5635 16.9503 55.9299 11.0635 64.6794C19.4963 58.4759 32.9713 54.9373 42.5686 58.7142Z" fill="#41965E"/>
            </svg>
        </a>
        <a class="navbar-brand" href="{% url 'home:home' %}"><span style="font-size:larger; color:#41965E;">Ecomment</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'community:index' %}">친환경 광장</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'news:index' %}"> 정보/뉴스</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account:mypage' %}" href="#">마이페이지</a>
                    {% else %}
                        <a class="nav-link" style="cursor: pointer" data-toggle="modal" data-target="#myModal"> 마이페이지 </a>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">경고</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    </div>
                                    <div class="modal-body">
                                        비회원은 권한이 없습니다.
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div></div>
                    {% endif %}
                </li>
            </ul>

            <div class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'account:logout' %}"><span style="color: #41965E;">{{ user.first_name }}님  </span>로그아웃</a></li>

                {% else %}
                    <li><a class="nav-link" href="{% url 'account:login' %}" style="color: #41965E;">로그인</a></li>
                    <li><a class="nav-link" href="{% url 'account:checkbox' %}">가입하기</a></li>
                {% endif %}
            </div>

        </div>

    </nav>
    {% block content %}
    {% endblock %}
</div>

</body>
</html>

templates/footer.html
{% block content %}
<footer style="flex-shrink: 0;">
<div class="foo_div my-5" style="width: 100%; padding : 0 5.5%;">
<svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M4.10685 3.33337H17.4402C18.3569 3.33337 19.1069 4.08337 19.1069 5.00004V15C19.1069 15.9167 18.3569 16.6667 17.4402 16.6667H4.10685C3.19019 16.6667 2.44019 15.9167 2.44019 15V5.00004C2.44019 4.08337 3.19019 3.33337 4.10685 3.33337Z" stroke="#8C8C8C" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M19.1069 5L10.7735 10.8333L2.44019 5" stroke="#8C8C8C" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
<p style="display: inline;font-size:10px;line-height: 100%;">&nbsp&nbsp&nbspContect&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp abc@contact.to.smn</p>
<br>
    <svg width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M14.5785 18.3325H14.6018C15.0418 18.3325 15.4576 18.1591 15.7726 17.8441L18.0326 15.5841C18.1101 15.5068 18.1715 15.415 18.2135 15.3139C18.2554 15.2128 18.277 15.1044 18.277 14.995C18.277 14.8855 18.2554 14.7771 18.2135 14.676C18.1715 14.575 18.1101 14.4831 18.0326 14.4058L14.6993 11.0725C14.622 10.995 14.5301 10.9336 14.429 10.8916C14.3279 10.8497 14.2196 10.8281 14.1101 10.8281C14.0007 10.8281 13.8923 10.8497 13.7912 10.8916C13.6901 10.9336 13.5983 10.995 13.521 11.0725L12.1926 12.4008C11.5768 12.2175 10.4276 11.8008 9.69929 11.0725C8.97096 10.3441 8.55429 9.19496 8.37096 8.57913L9.69929 7.25079C9.77674 7.17347 9.83819 7.08163 9.88012 6.98054C9.92204 6.87944 9.94362 6.77107 9.94362 6.66163C9.94362 6.55218 9.92204 6.44381 9.88012 6.34271C9.83819 6.24162 9.77674 6.14978 9.69929 6.07246L6.36596 2.73913C6.20664 2.58875 5.99586 2.50499 5.77679 2.50499C5.55772 2.50499 5.34694 2.58875 5.18762 2.73913L2.92846 4.99913C2.61179 5.31579 2.43346 5.75079 2.44012 6.19496C2.45929 7.38163 2.77346 11.5033 6.02179 14.7516C9.27012 18 13.3918 18.3133 14.5785 18.3325ZM5.77762 4.50663L7.93262 6.66163L6.85512 7.73913C6.75707 7.83691 6.68504 7.95767 6.64559 8.09042C6.60615 8.22316 6.60054 8.36366 6.62929 8.49913C6.64929 8.59496 7.13846 10.8675 8.52179 12.2508C9.90512 13.6341 12.1776 14.1233 12.2735 14.1433C12.4089 14.1722 12.5495 14.1667 12.6822 14.1272C12.815 14.0878 12.9358 14.0156 13.0335 13.9175L14.111 12.84L16.266 14.995L14.5943 16.6658C13.5543 16.6483 9.99596 16.3691 7.20012 13.5725C4.39512 10.7675 4.12346 7.19663 4.10679 6.17746L5.77762 4.50663ZM17.4393 9.16579H19.106C19.106 4.89079 15.8785 1.66663 11.5976 1.66663V3.33329C14.9826 3.33329 17.4393 5.78579 17.4393 9.16579Z" fill="#8C8C8C"/>
<path d="M11.606 6.66667C13.3585 6.66667 14.106 7.41417 14.106 9.16667H15.7726C15.7726 6.47917 14.2935 5 11.606 5V6.66667Z" fill="#8C8C8C"/>
</svg>
<p style="display: inline;font-size:10px;line-height: 100%;">&nbsp&nbsp&nbspContect&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp 02-123-456</p>
<br>
    <p style="display: inline;font-size:10px;">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp (c)sharesthnew</p>
</div>
</footer>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}


    <h2 style="font-family: Noto Sans KR; color: #000000; margin: 100px 0px 20px" id="home-comment1"> Ecomment 우리들의 친환경 이야기</h2>
    <h4 style="font-family: Noto Sans KR; color: #000000;" id="home-comment2">대한민국의 친환경, 자연주의, 유기농 문화를 만들어갑니다.</h4>

    <div style="margin: 60px 0px 120px;font-size: 14px;">
        <p style="line-height:200%; margin-bottom: -10%;">친환경제품에 대한 관심과 수요는 높아졌지만 통합된 커뮤니티가 부재하고,<br>
            소비자의 시각을 대변하는 외부적인 감시 필터가 부재합니다.<br>
            안전한 친환경을 같이 만들어갑니다.</p>
     <img src="/static/image/main.png" height="380" style="float:right;">
    </div>


    <p style="margin-bottom: 5%; text-align:center;font-family:Noto Sans KR;font-size:30px; color:#000000;">커뮤니티 사용 안내</p>
    <div class="d-flex justify-content-center">
    <img src="/static/image/community.png" height="200" style="float: left; margin:5% auto">

    <div style="float:left; border-left:1px solid #CDCDCD;height: 300px;"></div>

    <img src="/static/image/news.png" height="200" style="float:left; margin:5% auto">
    </div>

    <div class="d-flex justify-content-center">
    <div style="float: left; margin:5% auto">
    <p style="text-align:center;font-family:Noto Sans KR;font-size:16px; color:#000000;">친환경 광장</p>
    <p style="text-align:center;font-family:Noto Sans KR;font-weight: normal;font-size:14px;color: #757575;">친환경과 여러 제품들에 관해<br>
다양한 사람들과 자유롭게 이야기를 나누는 광장입니다.<br>
여러분의 친환경 이야기를 나누어보세요.</p>
    </div>
        <div style="float: left; margin:5% auto">

        <p style="text-align:center;font-family:Noto Sans KR;font-size:16px; color:#000000;">친환경 광장</p>
    <p style="text-align:center;font-family:Noto Sans KR;font-weight: normal;font-size:14px;">친환경 이슈, 기업과 제품, 관련 정책에 대한 정보와<br>
뉴스를 한눈에 볼 수 있습니다.<br>
최신 친환경 이슈를 놓치지 마세요.</p>
        </div>

        </div>

{% include 'footer.html' %}

{% endblock %}